controller_list:
  - name: fake_left_arm_controller
    joints:
      - l_arm_shz
      - l_arm_shx
      - l_arm_ely
      - l_arm_elx
      - l_arm_wry
      - l_arm_wrx
      - l_arm_wry2
  - name: fake_left_gripper_controller
    joints:
      - left_f0_j0
      - left_f0_j1
      - left_f0_j2
      - left_f1_j0
      - left_f1_j1
      - left_f1_j2
      - left_f2_j0
      - left_f2_j1
      - left_f2_j2
      - left_f3_j0
      - left_f3_j1
      - left_f3_j2